### ISSUE TITLE
address verbose logging

### ISSUE THREAD

**Issue by salv-orlando** [vmware/nsx-container-plugin-operator#100]
This message is repeated about twice every second

```
{"level":"info","ts":"2021-01-29T14:04:52.149Z","logger":"controller_configmap","msg":"configmap controller watching events in namespace nsx-system-operator"}
{"level":"info","ts":"2021-01-29T14:04:52.279Z","logger":"controller_configmap","msg":"configmap controller watching events in namespace nsx-system-operator"}
{"level":"info","ts":"2021-01-29T14:04:52.524Z","logger":"controller_configmap","msg":"configmap controller watching events in namespace nsx-system-operator"}
{"level":"info","ts":"2021-01-29T14:04:52.858Z","logger":"controller_configmap","msg":"configmap controller watching events in namespace nsx-system-operator"}
{"level":"info","ts":"2021-01-29T14:04:53.858Z","logger":"controller_configmap","msg":"configmap controller watching events in namespace nsx-system-operator"}
{"level":"info","ts":"2021-01-29T14:04:53.946Z","logger":"controller_configmap","msg":"configmap controller watching events in namespace nsx-system-operator"}
{"level":"info","ts":"2021-01-29T14:04:54.289Z","logger":"controller_configmap","msg":"configmap controller watching events in namespace nsx-system-operator"}
{"level":"info","ts":"2021-01-29T14:04:54.551Z","logger":"controller_configmap","msg":"configmap controller watching events in namespace nsx-system-operator"}
{"level":"info","ts":"2021-01-29T14:04:54.710Z","logger":"controller_configmap","msg":"configmap controller watching events in namespace nsx-system-operator"}
{"level":"info","ts":"2021-01-29T14:04:54.869Z","logger":"controller_configmap","msg":"configmap controller watching events in namespace nsx-system-operator"}
{"level":"info","ts":"2021-01-29T14:04:55.000Z","logger":"controller_configmap","msg":"configmap controller watching events in namespace nsx-system-operator"}
{"level":"info","ts":"2021-01-29T14:04:55.945Z","logger":"controller_configmap","msg":"configmap controller watching events in namespace nsx-system-operator"}
```

**Comment by timdengyun** [comment]
There are some points I'd like put:

Using cache.MultiNamespacedCacheBuilder in options when creating Manager in main.go is not a correct way to to manage MultiNamespae watch, this is better done via a Predicate. Moreover, we need to watch node change which is not namespace isolated and Network CRD type resource in openshift. Therefore, we need a cluster-scoped watch operator rather than multiple namespace operator. So only options attribute: Namespace as "" will be able to manage cluster scoped CRs.
Improve opportunities:

Controllers may Watch multiple Kinds of objects (e.g. Pods, ReplicaSets and Deployments), but they Reconciler only a single Type. Currently, our configmap controller Reconciler will watch four types of resources. It's better to have a Reconciler for each resource type. that is to say, It is better to write Controllers to perform an O(1) Reconciler N times (e.g. on N different objects) instead of performing an O(N) Reconciler 1 time (e.g. on a single object which manages N other objects)

There is a new func: NewPredicateFuncs in Predicate package from controller-runtime lib Version v0.6.2 onward, this is a simpler way compared to current fix approach. However, we are using v0.5.2 that is missing this new func. we could
refactor our code using this new one in the future.
